"""Shared bounded sample constants for data adapters."""

DEFAULT_ROW_SAMPLE_LIMIT = 50
DEFAULT_FEATURE_SAMPLE_LIMIT = 25
DEFAULT_VALUE_SAMPLE_LIMIT = 100

__all__ = ("DEFAULT_FEATURE_SAMPLE_LIMIT", "DEFAULT_ROW_SAMPLE_LIMIT", "DEFAULT_VALUE_SAMPLE_LIMIT")
