"""Deterministic verification for Elysia's governed runtime results.

The verifier checks structural coherence, tool/evidence receipts, memory and
privacy boundaries, model/compute outcome claims, and gear-selected review
depth.  It does not pretend that unsupported natural-language claims become
true merely because they were generated by a model.
"""

from typing import Any, Dict, List

from .evidence_verifier import verify_research_ticket_payload


def _normalize_memory_class_name(value: Any) -> str:
    """
    Normalize one memory-class value into a clean string.
    """
    return str(value or "").strip()


def _enum_payload_value(value: Any) -> str:
    """
    Return enum values as strings while leaving plain values stringified.
    """
    return str(getattr(value, "value", value) or "")


def verify_result(
    plan: Dict[str, Any],
    internal_result: Dict[str, Any],
) -> Dict[str, Any]:
    """Verify one runtime result at the depth selected by the Governor."""
    checks_passed: List[str] = []
    issues: List[str] = []

    if plan.get("intent"):
        checks_passed.append("plan_has_intent")
    else:
        issues.append("plan is missing intent")

    if plan.get("mode"):
        checks_passed.append("plan_has_mode")
    else:
        issues.append("plan is missing mode")

    if internal_result.get("status"):
        checks_passed.append("result_has_status")
    else:
        issues.append("internal result is missing status")

    if internal_result.get("note"):
        checks_passed.append("result_has_note")
    else:
        issues.append("internal result is missing note")

    retrieved_memory_count = int(plan.get("retrieved_memory_count", 0) or 0)
    uses_memory_context = bool(plan.get("uses_memory_context", False))
    memory_context_source = str(plan.get("memory_context_source", "") or "")
    reads_private_memory = bool(plan.get("reads_private_memory", False))

    memory_class = _normalize_memory_class_name(plan.get("memory_class", ""))
    primary_memory_class = _normalize_memory_class_name(
        plan.get("primary_memory_class", "")
    )
    forced_memory_class = _normalize_memory_class_name(
        plan.get("forced_memory_class", "")
    )
    memory_class_source = str(plan.get("memory_class_source", "") or "")
    memory_class_declared = bool(plan.get("memory_class_declared", False))
    memory_class_boundary_sensitive = bool(
        plan.get("memory_class_boundary_sensitive", False)
    )
    memory_class_requires_boundary_check = bool(
        plan.get("memory_class_requires_boundary_check", False)
    )

    if retrieved_memory_count >= 0:
        checks_passed.append("memory_count_is_nonnegative")
    else:
        issues.append("retrieved_memory_count must not be negative")

    if uses_memory_context and retrieved_memory_count > 0:
        checks_passed.append("memory_usage_matches_count")
    elif not uses_memory_context and retrieved_memory_count == 0:
        checks_passed.append("memory_usage_matches_count")
    else:
        issues.append(
            "uses_memory_context does not match retrieved_memory_count"
        )

    if retrieved_memory_count > 0:
        if memory_context_source and memory_context_source != "unknown":
            checks_passed.append("memory_source_present_when_memory_used")
        else:
            issues.append(
                "memory_context_source is missing despite retrieved memory"
            )
    else:
        checks_passed.append("memory_source_not_required_without_memory")

    if memory_class_declared:
        if memory_class:
            checks_passed.append("declared_memory_class_present")
        else:
            issues.append(
                "memory_class_declared is true but memory_class is missing"
            )
    else:
        checks_passed.append("memory_class_not_declared")

    if memory_class:
        if memory_class_source and memory_class_source != "unknown":
            checks_passed.append(
                "memory_class_source_present_when_memory_class_set"
            )
        else:
            issues.append(
                "memory_class_source is missing despite memory_class being set"
            )

        if primary_memory_class:
            checks_passed.append(
                "primary_memory_class_present_when_memory_class_set"
            )
        else:
            issues.append(
                "primary_memory_class is missing despite memory_class being set"
            )
    else:
        checks_passed.append("memory_class_source_not_required_without_memory_class")

    if forced_memory_class:
        if memory_class == forced_memory_class:
            checks_passed.append(
                "forced_memory_class_matches_selected_memory_class"
            )
        else:
            issues.append(
                "forced_memory_class does not match selected memory_class"
            )

        if memory_class_source == "forced_memory_class":
            checks_passed.append("forced_memory_class_source_is_explicit")
        else:
            issues.append(
                "memory_class_source should be forced_memory_class when forced_memory_class is set"
            )
    else:
        checks_passed.append("forced_memory_class_not_used")

    if memory_class_boundary_sensitive:
        if memory_class:
            checks_passed.append("boundary_sensitive_memory_class_is_named")
        else:
            issues.append(
                "memory_class_boundary_sensitive is true but memory_class is missing"
            )

        if reads_private_memory:
            checks_passed.append(
                "boundary_sensitive_memory_class_reads_private_memory"
            )
        else:
            issues.append(
                "boundary-sensitive memory_class should imply reads_private_memory"
            )
    else:
        checks_passed.append("memory_class_not_boundary_sensitive")

    if memory_class_requires_boundary_check:
        checks_passed.append("memory_class_boundary_check_flag_present")
    else:
        if forced_memory_class:
            issues.append(
                "forced_memory_class should require memory_class_requires_boundary_check"
            )
        else:
            checks_passed.append("memory_class_boundary_check_not_required")

    bounded_math_execution_candidate = bool(
        plan.get("bounded_math_execution_candidate", False)
    )
    math_execution = internal_result.get("math_execution")

    if bounded_math_execution_candidate:
        if isinstance(math_execution, dict):
            checks_passed.append("math_execution_summary_present")
            math_status = _enum_payload_value(math_execution.get("status", ""))
            math_used = bool(math_execution.get("used", False))

            if math_status:
                checks_passed.append("math_execution_status_present")
            else:
                issues.append("math execution summary is missing status")

            if math_used:
                checks_passed.append("math_execution_marked_used")
            else:
                issues.append("math execution candidate was not marked used")

            if math_status == "completed":
                if (
                    math_execution.get("result") is not None
                    or math_execution.get("numeric_result") is not None
                ):
                    checks_passed.append("math_execution_completed_with_result")
                else:
                    issues.append("completed math execution is missing result")
            elif math_status == "failed":
                if math_execution.get("errors"):
                    checks_passed.append("math_execution_failure_has_errors")
                else:
                    issues.append("failed math execution is missing errors")
            elif math_status in {"not_needed", ""}:
                issues.append("math execution candidate was not attempted")
            else:
                checks_passed.append("math_execution_status_recorded")
        else:
            issues.append("plan requested bounded math execution but result is missing")
    else:
        checks_passed.append("math_execution_not_required")

    bounded_data_execution_candidate = bool(
        plan.get("bounded_data_execution_candidate", False)
    )
    data_execution = internal_result.get("data_execution")

    if bounded_data_execution_candidate:
        if isinstance(data_execution, dict):
            checks_passed.append("data_execution_summary_present")
            data_status = _enum_payload_value(data_execution.get("status", ""))
            data_used = bool(data_execution.get("used", False))

            if data_status:
                checks_passed.append("data_execution_status_present")
            else:
                issues.append("data execution summary is missing status")

            if data_used:
                checks_passed.append("data_execution_marked_used")
            else:
                issues.append("data execution candidate was not marked used")

            if data_status == "completed":
                row_count = data_execution.get("row_count")
                column_count = data_execution.get("column_count")
                columns = data_execution.get("columns")

                if (
                    isinstance(row_count, int)
                    and row_count >= 0
                    and isinstance(column_count, int)
                    and column_count >= 0
                    and isinstance(columns, list)
                ):
                    checks_passed.append("data_execution_completed_with_table_shape")
                else:
                    issues.append("completed data execution is missing table shape")
            elif data_status in {"failed", "blocked"}:
                if data_execution.get("errors"):
                    checks_passed.append("data_execution_failure_has_errors")
                else:
                    issues.append("failed or blocked data execution is missing errors")
            elif data_status in {"not_needed", ""}:
                issues.append("data execution candidate was not attempted")
            else:
                checks_passed.append("data_execution_status_recorded")
        else:
            issues.append("plan requested bounded data execution but result is missing")
    else:
        checks_passed.append("data_execution_not_required")


    repo_context_candidate = bool(
        plan.get("repo_context_candidate", False)
    )
    repo_context = internal_result.get("repo_context")

    if repo_context_candidate:
        if isinstance(repo_context, dict):
            checks_passed.append("repo_context_summary_present")
            repo_status = _enum_payload_value(repo_context.get("status", ""))
            repo_used = bool(repo_context.get("used", False))

            if repo_status:
                checks_passed.append("repo_context_status_present")
            else:
                issues.append("repo context summary is missing status")

            if repo_used:
                checks_passed.append("repo_context_marked_used")
            else:
                issues.append("repo context candidate was not marked used")

            if repo_context.get("tool_kind") == "repo_context_gatherer":
                checks_passed.append("repo_context_tool_kind_recorded")
            else:
                issues.append("repo context tool kind is not repo_context_gatherer")

            if repo_context.get("read_only") is True:
                checks_passed.append("repo_context_read_only")
            else:
                issues.append("repo context must be read-only")

            if repo_context.get("shell_used") is False:
                checks_passed.append("repo_context_shell_not_used")
            else:
                issues.append("repo context must not use shell")

            if repo_context.get("network_access_used") is False:
                checks_passed.append("repo_context_network_not_used")
            else:
                issues.append("repo context must not use network access")

            if repo_context.get("mutated_files") is False:
                checks_passed.append("repo_context_mutated_no_files")
            else:
                issues.append("repo context must not mutate files")

            if repo_status in {"blocked", "failed"}:
                if repo_context.get("errors"):
                    checks_passed.append("repo_context_failure_has_errors")
                else:
                    issues.append("blocked or failed repo context is missing errors")
        else:
            issues.append("plan requested repo context but result is missing")
    else:
        checks_passed.append("repo_context_not_required")

    code_patch_plan_candidate = bool(
        plan.get("code_patch_plan_candidate", False)
    )
    code_patch_plan = internal_result.get("code_patch_plan")

    if code_patch_plan_candidate:
        if isinstance(code_patch_plan, dict):
            checks_passed.append("code_patch_plan_summary_present")
            patch_status = _enum_payload_value(code_patch_plan.get("status", ""))
            patch_used = bool(code_patch_plan.get("used", False))

            if patch_status:
                checks_passed.append("code_patch_plan_status_present")
            else:
                issues.append("code patch plan summary is missing status")

            if patch_status == "not_needed" and not patch_used:
                checks_passed.append("code_patch_plan_deferred_without_explicit_files")
            elif patch_used:
                checks_passed.append("code_patch_plan_marked_used")
            else:
                issues.append("code patch plan candidate has inconsistent used/status state")

            if patch_status == "completed":
                if code_patch_plan.get("approval_needed") is True:
                    checks_passed.append("code_patch_plan_requires_approval")
                else:
                    issues.append("completed code patch plan must require approval")

                if code_patch_plan.get("can_apply_patch") is False:
                    checks_passed.append("code_patch_plan_cannot_apply_patch")
                else:
                    issues.append("code patch plan must not be able to apply patches in v0")

                if code_patch_plan.get("patch_application_live") is False:
                    checks_passed.append("code_patch_plan_application_not_live")
                else:
                    issues.append("patch application must not be live in v0")

                if code_patch_plan.get("files_to_touch"):
                    checks_passed.append("code_patch_plan_files_to_touch_present")
                else:
                    issues.append("completed code patch plan is missing files_to_touch")

                if code_patch_plan.get("patch_plan"):
                    checks_passed.append("code_patch_plan_steps_present")
                else:
                    issues.append("completed code patch plan is missing patch_plan steps")

            if patch_status == "blocked":
                if code_patch_plan.get("errors"):
                    checks_passed.append("code_patch_plan_blocked_has_errors")
                else:
                    issues.append("blocked code patch plan is missing errors")

            if code_patch_plan.get("shell_execution_used") is False:
                checks_passed.append("code_patch_plan_shell_not_used")
            else:
                issues.append("code patch plan must not use shell execution")

            if code_patch_plan.get("network_access_used") is False:
                checks_passed.append("code_patch_plan_network_not_used")
            else:
                issues.append("code patch plan must not use network access")

            if code_patch_plan.get("mutated_files") is False:
                checks_passed.append("code_patch_plan_mutated_no_files")
            else:
                issues.append("code patch plan must not mutate files")

            if code_patch_plan.get("external_workers_used") is False:
                checks_passed.append("code_patch_plan_external_workers_not_used")
            else:
                issues.append("code patch plan must not use external coding workers")
        else:
            issues.append("plan requested code patch planning but result is missing")
    else:
        checks_passed.append("code_patch_plan_not_required")

    research_ticket_candidate = bool(
        plan.get("research_ticket_candidate", False)
    )
    research_ticket = internal_result.get("research_ticket")

    if research_ticket_candidate:
        if isinstance(research_ticket, dict):
            research_verification = verify_research_ticket_payload(research_ticket)
            checks_passed.append("research_ticket_summary_present")
            checks_passed.extend(research_verification["checks_passed"])
            issues.extend(research_verification["issues"])
        else:
            issues.append("plan requested research ticket but result is missing")
    else:
        checks_passed.append("research_ticket_not_required")

    aider_worker = internal_result.get("aider_worker")

    if isinstance(aider_worker, dict):
        checks_passed.append("aider_worker_summary_present")
        aider_status = _enum_payload_value(aider_worker.get("status", ""))

        if aider_status:
            checks_passed.append("aider_worker_status_present")
        else:
            issues.append("Aider worker summary is missing status")

        allowed_statuses = {
            "not_needed",
            "contract_only",
            "dry_run_ready",
            "blocked",
            "failed",
        }
        if aider_status in allowed_statuses:
            checks_passed.append("aider_worker_status_allowed")
        else:
            issues.append(f"Aider worker summary has unsupported status: {aider_status}")

        dangerous_false_fields = {
            "worker_used": "Aider worker skeleton must not claim worker execution",
            "aider_invoked": "Aider worker skeleton must not claim Aider invocation",
            "mutated_files": "Aider worker skeleton must not claim file mutation",
            "shell_used": "Aider worker skeleton must not claim shell use",
            "network_used": "Aider worker skeleton must not claim network use",
            "test_execution_used": "Aider worker skeleton must not claim test execution",
            "git_mutation_used": "Aider worker skeleton must not claim git mutation",
            "package_install_used": "Aider worker skeleton must not claim package installation",
            "external_model_used": "Aider worker skeleton must not claim external model use",
        }

        for field_name, issue_text in dangerous_false_fields.items():
            if aider_worker.get(field_name) is False:
                checks_passed.append(f"aider_worker_{field_name}_false")
            else:
                issues.append(issue_text)

        commands_run = aider_worker.get("commands_run")
        if isinstance(commands_run, list) and not commands_run:
            checks_passed.append("aider_worker_commands_run_empty")
        else:
            issues.append("Aider worker skeleton must not claim commands were run")

        tests_run = aider_worker.get("tests_run")
        if isinstance(tests_run, list) and not tests_run:
            checks_passed.append("aider_worker_tests_run_empty")
        else:
            issues.append("Aider worker skeleton must not claim tests were run")

        if aider_worker.get("approval_required") is True:
            checks_passed.append("aider_worker_future_mutation_requires_approval")
        else:
            issues.append(
                "Aider worker payload must require approval before any future mutation"
            )

        if aider_status == "blocked":
            if aider_worker.get("refusal_reasons") or aider_worker.get("errors"):
                checks_passed.append("aider_worker_blocked_has_refusal_truth")
            else:
                issues.append("blocked Aider worker payload is missing refusal reasons")
    else:
        checks_passed.append("aider_worker_not_required")

    governor = internal_result.get("governor")
    verification_depth = "standard"
    if isinstance(governor, dict):
        verification_depth = str(governor.get("verification_depth") or "standard")
        allowed_depths = {
            "deterministic", "basic", "standard", "enhanced",
            "independent_review", "evidence_and_tool_review",
        }
        if verification_depth in allowed_depths:
            checks_passed.append("governor_verification_depth_recognized")
        else:
            issues.append("Governor selected an unsupported verification depth")
        if governor.get("authority_increased") is False:
            checks_passed.append("governor_did_not_increase_authority")
        else:
            issues.append("Governor receipt must prove authority was not increased")

        result_gear = str(internal_result.get("reasoning_gear") or "")
        selected_gear = str(governor.get("selected_gear") or "")
        if result_gear and selected_gear and result_gear == selected_gear:
            checks_passed.append("runtime_gear_matches_governor")
        else:
            issues.append("Runtime reasoning gear does not match Governor receipt")

        compute = internal_result.get("compute")
        if isinstance(compute, dict) and compute.get("content_free") is True:
            checks_passed.append("compute_decision_is_content_free")
        else:
            issues.append("Governed runtime result is missing a content-free compute decision")

        context_receipt = internal_result.get("context_receipt")
        if isinstance(context_receipt, dict):
            checks_passed.append("context_receipt_present")
            if context_receipt.get("request_id"):
                checks_passed.append("context_receipt_has_request_id")
            else:
                issues.append("Context receipt is missing request identity")
            if isinstance(context_receipt.get("uncertainty"), dict):
                checks_passed.append("uncertainty_receipt_present")
            else:
                issues.append("Context receipt is missing uncertainty assessment")
        else:
            issues.append("Governed runtime result is missing its context receipt")

        result_status = str(internal_result.get("status") or "").casefold()
        allowed = bool(internal_result.get("allowed"))
        response_text = str(internal_result.get("response_text") or "").strip()
        if result_status == "ok":
            if allowed and response_text:
                checks_passed.append("successful_invocation_has_authorized_output")
            else:
                issues.append("Successful invocation is missing authorized output")
        elif result_status in {"blocked", "error", "not_invoked"}:
            checks_passed.append("non_success_invocation_status_is_explicit")

        provider_metadata = internal_result.get("provider_metadata")
        if isinstance(provider_metadata, dict) and provider_metadata.get("model_disagreement"):
            issues.append("Model disagreement requires additional verification")

        uncertainty = (
            context_receipt.get("uncertainty", {})
            if isinstance(context_receipt, dict)
            else {}
        )
        if isinstance(uncertainty, dict) and uncertainty.get("verifier_failure"):
            issues.append("Prior verifier failure remains unresolved")

        if verification_depth in {
            "enhanced", "independent_review", "evidence_and_tool_review"
        }:
            if isinstance(context_receipt, dict) and isinstance(
                context_receipt.get("admitted"), list
            ):
                checks_passed.append("enhanced_context_admission_reviewed")
            else:
                issues.append("Enhanced verification lacks an admission receipt")
            if internal_result.get("operational_self_model"):
                checks_passed.append("enhanced_operational_limits_reviewed")
            else:
                issues.append("Enhanced verification lacks operational limit truth")

        if verification_depth == "evidence_and_tool_review":
            research = internal_result.get("research")
            if isinstance(research, dict):
                state = str(research.get("state") or "not_needed").casefold()
                if state in {"complete", "completed"}:
                    if research.get("evidence_ids"):
                        checks_passed.append("completed_research_has_durable_evidence")
                    else:
                        issues.append("Completed research lacks durable evidence identifiers")
                elif state in {
                    "not_needed", "approval_required", "disabled", "blocked",
                    "cancelled", "failed", "degraded",
                }:
                    checks_passed.append("research_boundary_state_is_explicit")
                else:
                    issues.append("Research result has an unrecognized evidence state")
            else:
                issues.append("Research/Engineering verification lacks research truth")
    else:
        checks_passed.append("legacy_result_uses_standard_structural_verification")

    verified = len(issues) == 0

    return {
        "verified": verified,
        "verification_depth": verification_depth,
        "verification_pass_count": 1,
        "additional_verification_required": not verified,
        "provisional_result": not verified,
        "checks_passed": checks_passed,
        "issues": issues,
        "review_note": (
            "Deterministic governed verification checks structural coherence, "
            "tool and evidence receipts, memory/privacy boundaries, model and "
            "compute outcome truth, and the selected review depth. Unsupported "
            "semantic claims still require authoritative evidence."
        ),
    }


if __name__ == "__main__":
    demo_plan = {
        "intent": "tutoring",
        "mode": "tutor",
        "retrieved_memory_count": 2,
        "uses_memory_context": True,
        "memory_context_source": "local_session_journal_scaffold",
        "reads_private_memory": True,
        "memory_class": "working_memory",
        "primary_memory_class": "working_memory",
        "forced_memory_class": "working_memory",
        "memory_class_source": "forced_memory_class",
        "memory_class_declared": True,
        "memory_class_boundary_sensitive": False,
        "memory_class_requires_boundary_check": True,
    }

    demo_internal_result = {
        "status": "ok_scaffold",
        "note": "Internal scaffold result created before final response composition.",
    }

    print(verify_result(demo_plan, demo_internal_result))
