"""Generate shared Codev types. --check never writes; --online-root syncs Online."""
from __future__ import annotations

import argparse
from hashlib import sha256
import json
from pathlib import Path

from core.codev.contracts import CodevContracts

ROOT = Path(__file__).resolve().parents[1]


def typescript_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(typescript_type(value) for value in schema["anyOf"])
    kind = schema.get("type")
    if kind in {"string", "boolean", "null"}:
        return kind
    if kind in {"integer", "number"}:
        return "number"
    if kind == "array":
        return f"Array<{typescript_type(schema['items'])}>"
    if kind == "object":
        required = set(schema.get("required", []))
        return "{\n" + "\n".join(
            f"  {key}{'' if key in required else '?'}: {typescript_type(value)};"
            for key, value in schema.get("properties", {}).items()) + "\n}"
    raise ValueError(f"Unsupported schema node: {schema}")


def generated_files() -> tuple[str, str]:
    schema = CodevContracts.model_json_schema()
    canonical = json.dumps(schema, indent=2, sort_keys=True) + "\n"
    digest = sha256(canonical.encode()).hexdigest()
    ts = ("// Generated by Elysia scripts/generate_codev_contracts.py. Do not edit.\n"
          f"// Canonical JSON Schema SHA-256: {digest}\n"
          'export const CODEV_CONTRACT = "codev-client-1" as const;\n'
          f'export const CODEV_SCHEMA_SHA256 = "{digest}" as const;\n\n')
    for name, definition in sorted(schema["$defs"].items()):
        ts += f"export type {name} = {typescript_type(definition)};\n\n"
    return canonical, ts.rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--online-root", type=Path)
    args = parser.parse_args()
    schema, ts = generated_files()
    targets = {ROOT / "contracts/codev.schema.json": schema,
               ROOT / "apps/elysia-desktop/src/api/codevContracts.ts": ts}
    if args.online_root:
        targets[args.online_root / "src/shared/codev/contracts.ts"] = ts
        targets[args.online_root / "src/shared/codev/schema.json"] = schema
    for target, content in targets.items():
        if args.check:
            if not target.is_file() or target.read_text() != content:
                raise SystemExit(f"Codev contract drift: {target.relative_to(target.anchor)}")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
    print(f"Codev contracts {'verified' if args.check else 'generated'}: {len(targets)} files")


if __name__ == "__main__":
    main()
